### ISSUE TITLE
Ignore io-visualization.Rproj

### ISSUE THREAD

**Issue by vwmaus** [fineprint-global/io-visualization#1]
@Gutschlhofer the repo looks very good already. I would delete the Rstudio file `io-visualization.Rproj` and add the line `*.Rproj` to `.gitignore` at 
https://github.com/fineprint-global/io-visualization/blob/d430032e1ab241c810fddf15f141cec8b4a4a1f1/.gitignore#L17

**Comment by vwmaus** [comment]
for security, I would also remove the files `.env` and `.Renviron` from the repo and add them to `.gitignore`. In `README.md` you can add instructions for the users to create these files.

**Comment by Gutschlhofer** [comment]
There are various discussions online in favor of including the `.Rproj` file, that's why I lately am positive towards including them in git repos, e.g. https://community.rstudio.com/t/should-rproj-files-be-added-to-gitignore/1269/2

As for the second point: yes, I'll definitely ignore them once I add actual passwords, I just wanted these examples to be here to allow the early stages of the repo to serve as a template for other projects as well, but a description in the `README.md` does the trick, too, you are right!

**Comment by Gutschlhofer** [comment]
3964600 added `.env` and `.Renviron` to the `.gitignore`, as explained above I will (for now) keep the `.Rproj` so I consider this issue closed.
